name: 'freeasphosting deploy'
description:
  'This action deployed your zip file to freeasphosting via a post request'
author: '@igubanov'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

  login:
    description: 'Login for freeasphosting.net (like on the site)'
    required: true
  password:
    description: 'Password for freeasphosting.net (like on the site)'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
